version: "3.4"
services:
  baserow:
    build: .
    ports:
      - "8280:80"
      - "8243:443"
    volumes:
      - baserow_data:/baserow/data
    environment:
      BASEROW_PUBLIC_URL: https://baserow-free.automateme.ru

volumes:
  baserow_data:
