version: '3'
services:
  baserow:
    container_name: baserow
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BASEROW_PUBLIC_URL=${BASEROW_PUBLIC_URL:-http://localhost}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - baserow_data:/baserow/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/_health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    dns:
      - 83.220.169.155
      - 212.109.195.93

volumes:
  baserow_data: null
