version: "3.4"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - BASEROW_PUBLIC_URL=http://localhost:8280
      - BASEROW_CADDY_ADDRESSES=:80
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=baserow
      - DATABASE_USER=baserow
      - DATABASE_PASSWORD=baserow
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASSWORD=baserow
      - REDIS_PROTOCOL=redis
      - BASEROW_AMOUNT_OF_WORKERS=1
      - BASEROW_ROW_PAGE_SIZE_LIMIT=200
      - BASEROW_FRONTEND_URL=http://localhost:8280
      - BASEROW_BACKEND_DEBUG=True
      - PRIVATE_BACKEND_URL=http://backend:8000
      - PRIVATE_FRONTEND_URL=http://web-frontend:3000
      - BASEROW_EVENT_REDIS_URL=redis://default:baserow@redis:6379
      - BASEROW_ENABLE_SECURE_PROXY_SSL_HEADER=True
      - BASEROW_EXTRA_ALLOWED_HOSTS=backend,localhost,127.0.0.1
      - BASEROW_OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - BASEROW_ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - BASEROW_MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
    depends_on:
      - db
      - redis

  web-frontend:
    build:
      context: .
      dockerfile: ./web-frontend/Dockerfile
    environment:
      - BASEROW_PUBLIC_URL=http://localhost:8280
      - PRIVATE_BACKEND_URL=http://backend:8000
      - PRIVATE_FRONTEND_URL=http://web-frontend:3000
      - BASEROW_DISABLE_PUBLIC_URL_CHECK=true
      - BASEROW_ENABLE_SECURE_PROXY_SSL_HEADER=True
      - BASEROW_FRONTEND_SAME_SITE_COOKIE=Lax
      - BASEROW_EXTRA_ALLOWED_HOSTS=backend,localhost,127.0.0.1
    depends_on:
      - backend

  celery:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery-worker
    environment:
      - BASEROW_PUBLIC_URL=http://localhost:8280
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=baserow
      - DATABASE_USER=baserow
      - DATABASE_PASSWORD=baserow
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASSWORD=baserow
      - REDIS_PROTOCOL=redis
      - PRIVATE_BACKEND_URL=http://backend:8000
      - BASEROW_EVENT_REDIS_URL=redis://default:baserow@redis:6379
      - BASEROW_ENABLE_SECURE_PROXY_SSL_HEADER=True
      - BASEROW_EXTRA_ALLOWED_HOSTS=backend,localhost,127.0.0.1
      - BASEROW_OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - BASEROW_ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - BASEROW_MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
    depends_on:
      - backend

  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=baserow
      - POSTGRES_PASSWORD=baserow
      - POSTGRES_DB=baserow
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    command: redis-server --requirepass baserow
    volumes:
      - redisdata:/data

  proxy:
    image: caddy:2
    ports:
      - "8280:80"
      - "8243:443"
    environment:
      - BASEROW_PUBLIC_URL=http://localhost:8280
      - BASEROW_CADDY_ADDRESSES=:80
    volumes:
      - ./deploy/all-in-one/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - web-frontend

volumes:
  pgdata:
  redisdata:
