version: '3'
services:
  baserow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8280:80'
      - '8243:443'
    environment:
      - BASEROW_PUBLIC_URL=https://baserow-free.automateme.ru
    volumes:
      - baserow_data:/baserow/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/_health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    dns:
      - 83.220.169.155
      - 212.109.195.93

volumes:
  baserow_data:
